### PR TITLE
WIP: hdfs file node

### PR DESCRIPTION
**Pull request by tanmaykm**
*do not merge*

First attempt at getting HDFS files to work with ComputeFramework.

Couldn't avoid quite a bit of duplication, I think data nodes need further generalization. Also, we should have extensions like this be built as separate packages. Will try these next.

### CODE REVIEW

**Comment by shashi** [comment]
This is looking good!

I think we can make SplitNode take either a FileNode or a HDFSFileNode and still work with the same compute method.

I'll try to do this now.

**Comment by shashi** [comment]
Can you take a look?

**Comment by shashi** [comment]
This is very obsolete by now. Let's start over.

**Comment by ViralBShah** [comment]
Yes - worth getting it in.

**Pull request closed without merging**
