### PR TITLE
GPU support for ComputeFramework

### PR DESCRIPTION
**Pull request by ranjanan**
Add GPU support using ArrayFire

### CODE REVIEW

**Comment by shashi** [comment]
What do you think we should do about the ArrayFire dependency? probably [`@require`](https://github.com/MikeInnes/Requires.jl)?

can you create a branch on this repo? I can then add my commits

**Comment by ranjanan** [comment]
Yeah, `@require` seems like it's worth trying out. Shall I delete this pull request and create a branch on the repo, which we can then collab on?

**Comment by shashi** [comment]
yea sounds good

**Comment by ViralBShah** [comment]
Doesn't `@require` will break precompilation.

**Comment by shashi** [comment]
On 0.4 at least if you don't have precompile directive, it does work.

The alternative is having users compile ArrayFire to get CF to work, or have a package for interop. Another case for https://github.com/JuliaLang/julia/issues/15705

**Pull request closed without merging**
